"""
Spawn a native desktop terminal running OpenCode with the agent_config's
system_prompt, skill, env, and working dir injected.
"""
from __future__ import annotations
import os
import shlex
import sqlite3
import subprocess
import time
import uuid
from pathlib import Path
from typing import Optional
from uuid import UUID

from backend.db import queries
from backend.graph.state import ConductorState
from backend.graph.graph import prepare_graph

WORKSPACE_ROOT = Path(os.environ["WORKSPACE_ROOT"])
TERMINAL_CMD = os.environ.get("TERMINAL_CMD", "gnome-terminal")
OPENCODE_DB_PATH = Path(os.environ.get("OPENCODE_DB_PATH", "~/.local/share/opencode/opencode.db")).expanduser()


# ──────────────────────── AGENTS.md injection ────────────────────────

def write_agents_md(
    repo_path: Path,
    *,
    project_system_prompt: Optional[str],
    config_system_prompt: Optional[str],
    skill_path: Optional[str],
) -> None:
    """
    Compose AGENTS.md (OpenCode's project context file) from:
    - the project-level system_prompt (long-lived per project)
    - the agent_config's system_prompt (short-lived per role)
    - a reference to the SKILL.md
    """
    parts: list[str] = []
    parts.append("# AGENTS.md — generated by AIPC Conductor\n")
    parts.append("DO NOT EDIT BY HAND. This file is rewritten on each spawn.\n")

    if project_system_prompt:
        parts.append("\n## Project context\n")
        parts.append(project_system_prompt.strip())
        parts.append("")

    if config_system_prompt:
        parts.append("\n## Role instructions\n")
        parts.append(config_system_prompt.strip())
        parts.append("")

    if skill_path and Path(skill_path).is_file():
        try:
            content = Path(skill_path).read_text(encoding="utf-8")
            parts.append("\n## Skill\n")
            parts.append(content.strip())
            parts.append("")
        except Exception:
            pass

    (repo_path / "AGENTS.md").write_text("\n".join(parts), encoding="utf-8")


# ──────────────────────── git ops ────────────────────────

def ensure_repo(project_id: str) -> Path:
    """Ensure the workspace git repo exists. Returns absolute path."""
    repo = WORKSPACE_ROOT / project_id
    if not (repo / ".git").is_dir():
        repo.mkdir(parents=True, exist_ok=True)
        subprocess.run(["git", "init", "-b", "main"], cwd=repo, check=True)
        readme = repo / "README.md"
        if not readme.exists():
            readme.write_text(f"# {project_id}\n", encoding="utf-8")
        subprocess.run(["git", "add", "."], cwd=repo, check=True)
        subprocess.run(
            ["git", "commit", "-m", "Initial commit (conductor bootstrap)"],
            cwd=repo, check=True
        )
    return repo


def ensure_branch(repo_path: Path, branch: str, base: str = "main") -> None:
    """Checkout branch (create from base if needed)."""
    cur = subprocess.run(
        ["git", "branch", "--show-current"], cwd=repo_path, capture_output=True, text=True
    ).stdout.strip()
    if cur == branch:
        return

    exists = subprocess.run(
        ["git", "rev-parse", "--verify", branch], cwd=repo_path, capture_output=True
    ).returncode == 0

    if exists:
        subprocess.run(["git", "checkout", branch], cwd=repo_path, check=True)
    else:
        subprocess.run(["git", "checkout", "-b", branch, base], cwd=repo_path, check=True)


# ──────────────────────── spawn ────────────────────────

def build_opencode_command(
    *,
    model_preference: Optional[str],
) -> str:
    """Construct the opencode command string."""
    parts = ["opencode"]
    if model_preference:
        parts.extend(["--model", model_preference])
    cmd = " ".join(shlex.quote(p) for p in parts)
    return cmd


def discover_session_id(
    *,
    spawned_after: float,
    retries: int = 6,
    delay: float = 1.0,
) -> Optional[str]:
    """
    Poll OpenCode's SQLite DB for a session created after `spawned_after`.
    OpenCode creates the session row on startup, so we poll briefly.
    Returns the session.id (e.g. 'ses_1bc5cb...') or None.
    """
    if not OPENCODE_DB_PATH.is_file():
        return None
    for attempt in range(retries):
        try:
            conn = sqlite3.connect(str(OPENCODE_DB_PATH))
            cur = conn.execute(
                "SELECT id FROM session WHERE time_created > ? ORDER BY time_created DESC LIMIT 1",
                (int(spawned_after * 1000),),
            )
            row = cur.fetchone()
            conn.close()
            if row:
                return row[0]
        except sqlite3.Error:
            pass
        if attempt < retries - 1:
            time.sleep(delay)
    return None


def spawn_terminal(
    *,
    cwd: Path,
    command: str,
    env: dict[str, str],
    title: str,
) -> subprocess.Popen:
    """
    Open a native terminal window running `command` in `cwd` with `env`.
    Backgrounded — does NOT wait.
    """
    shell_script = (
        f"cd {shlex.quote(str(cwd))} && "
        f"{command}; "
        "echo; echo '--- session ended ---'; exec bash"
    )

    full_env = os.environ.copy()
    full_env.update(env)

    if TERMINAL_CMD == "gnome-terminal":
        argv = [
            "gnome-terminal",
            "--title", title,
            "--",
            "bash", "-c", shell_script,
        ]
    elif TERMINAL_CMD == "xterm":
        argv = ["xterm", "-T", title, "-e", "bash", "-c", shell_script]
    elif TERMINAL_CMD == "konsole":
        argv = ["konsole", "--new-tab", "-p", f"tabtitle={title}", "-e", "bash", "-c", shell_script]
    elif TERMINAL_CMD == "alacritty":
        argv = ["alacritty", "-t", title, "-e", "bash", "-c", shell_script]
    else:
        argv = [TERMINAL_CMD, "-e", "bash", "-c", shell_script]

    return subprocess.Popen(
        argv,
        env=full_env,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )


# ──────────────────────── orchestration ────────────────────────

def spawn_for_task(
    *,
    task_id: UUID,
    agent_config_id: str,
    input_spec: Optional[dict] = None,
    preceding_trace_id: Optional[UUID] = None,
) -> dict:
    """
    Full spawn flow:
      1. Lookup task, project, session, agent_config
      2. Ensure repo + branch
      3. Build input_spec (or use provided)
      4. Invoke prepare_graph to create trace row
      5. Write AGENTS.md
      6. Spawn terminal (OpenCode creates its own session naturally)
      7. Poll OpenCode DB to discover the real session.id
      8. Update trace row with discovered cli_session_id
    Returns dict with trace_id, cli_session_id, repo_path.
    """
    # 1. Lookup
    task = queries.get_task(task_id)
    if task is None:
        raise ValueError(f"task not found: {task_id}")

    project_id = task["project_id"]
    branch = task["session_id"]

    with queries.conn() as c, c.cursor() as cur:
        cur.execute("SELECT * FROM projects WHERE project_id = %s", (project_id,))
        project = cur.fetchone()
        if project is None:
            raise ValueError(f"project not found: {project_id}")

    config = queries.get_agent_config(agent_config_id)
    if config is None:
        raise ValueError(f"agent_config not found or inactive: {agent_config_id}")

    # 2. Ensure repo + branch
    repo_path = ensure_repo(project_id)
    ensure_branch(repo_path, branch)

    # 3. Build input_spec if not provided
    if input_spec is None:
        input_spec = {
            "spec_version": "1.0.0",
            "task_id": str(task_id),
            "user_intent": task["user_intent"],
            "domain": config["domain"],
            "intent_type": "implement",
        }

    # 4. Prepare graph creates the trace row
    state = ConductorState(
        task_id=task_id,
        project_id=project_id,
        session_id=branch,
        agent_config_id=agent_config_id,
        input_spec=input_spec,
        preceding_trace_id=preceding_trace_id,
    )
    result = prepare_graph.invoke(state)
    if isinstance(result, dict):
        trace_id = result.get("trace_id")
        errs = result.get("errors") or []
    else:
        trace_id = result.trace_id
        errs = result.errors
    if errs:
        raise RuntimeError(f"prepare failed: {errs}")

    # 5. Write AGENTS.md
    write_agents_md(
        repo_path,
        project_system_prompt=project.get("system_prompt"),
        config_system_prompt=config.get("system_prompt"),
        skill_path=config.get("skill_path"),
    )

    # 6. Spawn — OpenCode creates its own session with a ses_xxx id
    command = build_opencode_command(
        model_preference=config.get("model_preference"),
    )

    spawned_at = time.time()
    title = f"[{project_id}] {branch} — {config['role']}"
    spawn_terminal(cwd=repo_path, command=command, env={
        "AIPC_TRACE_ID": str(trace_id),
        "AIPC_TASK_ID": str(task_id),
        "AIPC_SESSION_ID": branch,
        "AIPC_PROJECT_ID": project_id,
        "AIPC_AGENT_CONFIG_ID": agent_config_id,
    }, title=title)

    # 7. Discover the real session.id from OpenCode's SQLite DB
    cli_session_id = discover_session_id(spawned_after=spawned_at)
    if not cli_session_id:
        # Fallback: generate a placeholder — adapter can still glob by recency
        cli_session_id = f"ses_{uuid.uuid4().hex}"

    # 8. Update trace row with the discovered session id
    queries.update_trace_status(
        trace_id,
        status="running",
        cli_session_id=cli_session_id,
    )

    with queries.conn() as c, c.cursor() as cur:
        cur.execute(
            "UPDATE tasks SET status = 'in_progress' WHERE task_id = %s AND status = 'open'",
            (str(task_id),),
        )

    return {
        "trace_id": str(trace_id),
        "cli_session_id": cli_session_id,
        "repo_path": str(repo_path),
        "branch": branch,
    }
