from __future__ import annotations

"""File 04 — Agent-config generation on miss (proposal → validate → ratify → persist).

When no existing agent_config can staff a node (caught by File 03's staffing
gate), this module generates a new one as a PROPOSAL, validates it against
real backend capabilities, and queues it for human ratification.

Registry-first: generation fires ONLY on genuine no-fit.
"""

import json
import logging
from typing import Any

from pydantic import BaseModel, Field

from backend.planning.meta_planner.llm import call_llm_structured, get_meta_planner_model

logger = logging.getLogger(__name__)


class AgentConfigProposal(BaseModel):
    """A proposed agent_config to be validated and ratified.

    Generated by the LLM when no existing config can staff a node.
    """
    agent_config_id: str = Field(
        description="Unique identifier, e.g. 'opencode:frontend-executor'",
    )
    role: str = Field(description="Role: executor | planner | reviewer")
    domain: str = Field(description="Domain tag, e.g. 'frontend', 'data'")
    capability_summary: list[str] = Field(
        description="Capability tags, e.g. ['frontend', 'tests', 'ui']",
    )
    system_prompt: str = Field(
        description="System prompt for the agent (hard rules, stack, conventions)",
    )
    skill_outline: str = Field(
        description="Brief outline of the skill/references this agent needs",
    )
    execution: dict[str, str] = Field(
        description="Backend config: {'backend': 'opencode', 'model_preference': '...'}",
    )
    default_checks: dict[str, list[dict[str, Any]]] = Field(
        description="Default L1 and L2 checks: {'l1': [...], 'l2': [...]}",
    )


AGENTGEN_PROMPT = """\
You are an agent-config generator. A plan node needs capabilities no existing
config provides. Draft a new agent_config proposal.

Node task:
{task}

Required capabilities:
{caps}

Domain profile:
{domain}
Conventions for this domain:
{conventions}

Produce a complete AgentConfigProposal with:

- agent_config_id: unique, follows "<cli>:<domain>-<role>" convention, e.g. "opencode:frontend-executor"
- role: the node's required role
- domain: the domain this config targets
- capability_summary: list of capability tags this config provides (MUST include the required caps)
- system_prompt: brief instructions for the agent (tech stack, hard rules, conventions to follow)
- skill_outline: what skills/references the agent needs
- execution: backend = "opencode", model_preference = "deepseek/deepseek-chat"
- default_checks: l1 and l2 checks appropriate for this domain (l1: shell/file checks, l2: rubric items)

The capability_summary MUST cover all the required capabilities listed above.
The agent_config_id MUST NOT collide with existing configs (check the roster).

Return the JSON object matching the AgentConfigProposal schema."""


def _get_roster_ids() -> set[str]:
    """Load existing agent_config_ids from the database."""
    import os
    import psycopg
    try:
        dsn = os.environ["DATABASE_URL"]
        with psycopg.connect(dsn) as conn, conn.cursor() as cur:
            cur.execute("SELECT agent_config_id FROM agent_configs WHERE active = TRUE")
            return {row[0] for row in cur.fetchall()}
    except Exception:
        logger.warning("Could not query roster — assuming empty")
        return set()


def needs_new_agent_config(node_task: str, roster: list[dict[str, Any]] | None = None) -> list[str] | None:
    """Check if any existing roster entry can staff the required capabilities.

    Args:
        node_task: The node's task text.
        roster: List of agent_config dicts with ``capability_summary``.
                If None, queries the DB.

    Returns:
        List of required capabilities if NO existing config fits, or None if a
        capable config exists (registry-first).
    """
    from backend.evaluator.plan_evaluator import _infer_required_caps
    required = _infer_required_caps(node_task)
    if not required:
        return None  # No specific capabilities needed — any config works

    if roster is None:
        roster = _load_roster_from_db()

    for ac in roster:
        ac_caps = set(ac.get("capability_summary") or ac.get("capabilities", []))
        if required & ac_caps:
            return None  # An existing config fits → registry-first

    return list(required)


def _load_roster_from_db() -> list[dict[str, Any]]:
    """Load all active agent_configs with capability data from the DB."""
    import os
    import psycopg
    from backend.evaluator.plan_evaluator import infer_agent_config_capabilities
    try:
        dsn = os.environ["DATABASE_URL"]
        with psycopg.connect(dsn) as conn, conn.cursor() as cur:
            cur.execute(
                "SELECT agent_config_id, domain, role FROM agent_configs WHERE active = TRUE",
            )
            rows = cur.fetchall()
            roster = []
            for row in rows:
                ac_id, domain, role = row[0], row[1], row[2]
                caps = infer_agent_config_capabilities(ac_id, domain, role)
                roster.append({
                    "agent_config_id": ac_id,
                    "domain": domain,
                    "role": role,
                    "capability_summary": caps,
                })
            return roster
    except Exception:
        logger.warning("Could not load roster from DB")
        return []


def propose_agent_config(
    task: str,
    required_caps: list[str],
    domain_profile: dict[str, Any] | None = None,
) -> AgentConfigProposal | None:
    """Generate a new agent_config proposal via LLM.

    Args:
        task: The node's task text.
        required_caps: Capabilities the new config must provide.
        domain_profile: Optional domain profile dict for conventions context.

    Returns:
        An ``AgentConfigProposal`` or None on failure.
    """
    domain_str = domain_profile.get("domain", "generic") if domain_profile else "generic"
    conventions = domain_profile.get("conventions", []) if domain_profile else []

    prompt = AGENTGEN_PROMPT.format(
        task=task,
        caps=", ".join(required_caps),
        domain=domain_str,
        conventions="; ".join(conventions) if conventions else "(none)",
    )

    try:
        model_cfg = get_meta_planner_model()
        proposal = call_llm_structured(prompt, schema=AgentConfigProposal, model_cfg=model_cfg)
        return proposal
    except Exception as exc:
        logger.error("Agent config generation failed: %s", exc)
        return None


def _existing_ids() -> set[str]:
    return _get_roster_ids()


def validate_proposal(proposal: AgentConfigProposal) -> list[str]:
    """Validate a generated proposal against real backend capabilities.

    Checks:
    1. Backend can realize claimed capabilities.
    2. Proposal is complete (has system_prompt, default_checks L1).
    3. agent_config_id doesn't collide with existing configs.

    Args:
        proposal: The proposal to validate.

    Returns:
        List of failure descriptions (empty = valid).
    """
    fails: list[str] = []

    # Check completeness
    if not proposal.system_prompt or len(proposal.system_prompt.strip()) < 20:
        fails.append("incomplete proposal: system_prompt is missing or too short")
    l1_checks = proposal.default_checks.get("l1", [])
    if not l1_checks:
        fails.append("incomplete proposal: no L1 default_checks")
    l2_checks = proposal.default_checks.get("l2", [])
    if not l2_checks:
        fails.append("incomplete proposal: no L2 default_checks")

    # Check capability coverage
    if not proposal.capability_summary:
        fails.append("incomplete proposal: capability_summary is empty")

    # Check id collision
    if proposal.agent_config_id in _existing_ids():
        fails.append(f"id collision: '{proposal.agent_config_id}' already exists")

    # Backend capability check (basic)
    backend = proposal.execution.get("backend", "")
    if backend and backend not in ("opencode", "hermes"):
        fails.append(f"unsupported backend: '{backend}'")

    return fails


def submit_proposal(proposal: AgentConfigProposal) -> dict[str, Any]:
    """Validate a proposal and return result for human ratification.

    Args:
        proposal: The proposal to submit.

    Returns:
        Dict with ``valid`` (bool), ``failures`` (list[str]), and
        ``proposal`` (dict) keys.
    """
    failures = validate_proposal(proposal)
    if failures:
        logger.warning("Proposal '%s' rejected: %s", proposal.agent_config_id, failures)
        return {"valid": False, "failures": failures, "proposal": proposal.model_dump()}

    logger.info(
        "Proposal '%s' valid — queued for human ratification",
        proposal.agent_config_id,
    )
    return {
        "valid": True,
        "failures": [],
        "proposal": proposal.model_dump(),
    }
