BEGIN;

ALTER TABLE runs ADD COLUMN IF NOT EXISTS master_commit TEXT;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS goal_kind TEXT NOT NULL DEFAULT '';
ALTER TABLE runs ADD COLUMN IF NOT EXISTS env TEXT NOT NULL DEFAULT 'staging';

COMMIT;
